import type { GarmentTypeConfig } from "../garment-types";

export const SAUDI_CONFIG: GarmentTypeConfig = {
  id: "saudi",
  label: "الجلابية السعودي",
  measurements: [
    {
      name: "length",
      label: "الطول",
      unit: "inch",
      required: true,
      min: 20,
      max: 80,
    },
    {
      name: "sleeve",
      label: "الكم",
      unit: "cm",
      required: true,
      min: 30,
      max: 80,
    },
    {
      name: "sleeve_width",
      label: "وسع الكم",
      unit: "cm",
      required: true,
      min: 10,
      max: 60,
    },
    {
      name: "shoulder",
      label: "الكتف",
      unit: "inch",
      required: true,
      min: 10,
      max: 30,
    },
    {
      name: "neck",
      label: "الرقبة",
      unit: "inch",
      required: true,
      min: 10,
      max: 30,
    },
    {
      name: "bottom_width",
      label: "الأتك",
      unit: "inch",
      required: true,
      min: 10,
      max: 50,
    },
    {
      name: "pocket",
      label: "الخزنة",
      unit: "inch",
      required: false,
      min: 5,
      max: 30,
    },
    {
      name: "cuff",
      label: "الأشتيك",
      unit: "inch",
      required: false,
      min: 5,
      max: 20,
    },
    {
      name: "pocket_drop",
      label: "آخر سقوط الجيب",
      unit: "inch",
      required: false,
      min: 5,
      max: 30,
    },
  ],
};
